[all]
prod-k8s-master01	      ansible_host=10.10.20.104    ip=10.10.20.104
prod-k8s-master02	      ansible_host=10.10.20.105    ip=10.10.20.105
prod-k8s-master03	      ansible_host=10.10.20.106    ip=10.10.20.106
prod-k8s-ingress01	    ansible_host=10.10.20.107    ip=10.10.20.107
prod-k8s-ingress02	    ansible_host=10.10.20.108    ip=10.10.20.108
prod-k8s-ingress03	    ansible_host=10.10.20.109    ip=10.10.20.109
prod-k8s-worker-tool	  ansible_host=10.10.20.110    ip=10.10.20.110
prod-k8s-worker01	      ansible_host=10.10.20.111    ip=10.10.20.111
prod-k8s-worker02	      ansible_host=10.10.20.112    ip=10.10.20.112
prod-k8s-worker03	      ansible_host=10.10.20.113    ip=10.10.20.113
prod-k8s-worker04	      ansible_host=10.10.20.114    ip=10.10.20.114
prod-k8s-worker05	      ansible_host=10.10.20.115    ip=10.10.20.115
prod-k8s-worker06	      ansible_host=10.10.20.116    ip=10.10.20.116
prod-k8s-worker07	      ansible_host=10.10.20.117    ip=10.10.20.117
prod-k8s-worker08	      ansible_host=10.10.20.118    ip=10.10.20.118
prod-k8s-worker09	      ansible_host=10.10.20.119    ip=10.10.20.119
prod-k8s-worker10	      ansible_host=10.10.20.120    ip=10.10.20.120
prod-k8s-worker11	      ansible_host=10.10.20.121    ip=10.10.20.121
prod-k8s-worker12	      ansible_host=10.10.20.122    ip=10.10.20.122

[kube-master]
prod-k8s-master01
prod-k8s-master02
prod-k8s-master03

[kube-node]
prod-k8s-ingress01
prod-k8s-ingress02
prod-k8s-ingress03
prod-k8s-worker-tool
prod-k8s-worker01
prod-k8s-worker02
prod-k8s-worker03
prod-k8s-worker04
prod-k8s-worker05
prod-k8s-worker06
prod-k8s-worker07
prod-k8s-worker08
prod-k8s-worker09
prod-k8s-worker10
prod-k8s-worker11
prod-k8s-worker12

[etcd]
prod-k8s-master01
prod-k8s-master02
prod-k8s-master03

[k8s_cluster:children]
kube-node
kube-master

[calico-rr]

[vault]
prod-k8s-master01
prod-k8s-master02
prod-k8s-master03
prod-k8s-ingress01
prod-k8s-ingress02
prod-k8s-ingress03
prod-k8s-worker-tool
prod-k8s-worker01
prod-k8s-worker02
prod-k8s-worker03
prod-k8s-worker04
prod-k8s-worker05
prod-k8s-worker06
prod-k8s-worker07
prod-k8s-worker08
prod-k8s-worker09
prod-k8s-worker10
prod-k8s-worker11
prod-k8s-worker12